version: '3.8'

services:
  pdf-extractor:
    build: .
    container_name: pdf-extractor
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./main.py:/app/main.py
      - ./pdf_processor.py:/app/pdf_processor.py
      - pdf_cache:/app/cache
      - model_cache:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - TRANSFORMERS_CACHE=/app/cache/transformers
      - TORCH_HOME=/app/cache/torch
      - HF_HOME=/app/cache/huggingface
      - EASYOCR_MODULE_PATH=/app/cache/easyocr
      - SENTENCEPIECE_DATA_DIR=/app/cache/sentencepiece
    networks:
      - pdf-extractor-network

volumes:
  pdf_cache:
    name: pdf_extractor_cache
  model_cache:
    name: pdf_extractor_model_cache

networks:
  pdf-extractor-network:
    driver: bridge 